# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 20:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст ответа')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата добавления ответа')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор ответа.')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='заголовок вопроса')),
                ('text', models.TextField(verbose_name='полный текст вопроса')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата добавления вопроса')),
                ('rating', models.IntegerField(verbose_name='рейтинг вопроса')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='автор вопроса')),
                ('likes', models.ManyToManyField(related_name='liked_questions', to=settings.AUTH_USER_MODEL, verbose_name='список пользователей, поставивших "лайк"')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='qa.Question', verbose_name='вопрос, к которому относится ответ'),
        ),
    ]
