# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 21:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-added_at']},
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.Question', verbose_name='вопрос, к которому относится ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_questions', to=settings.AUTH_USER_MODEL, verbose_name='список пользователей, поставивших "лайк"'),
        ),
        migrations.AlterField(
            model_name='question',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='рейтинг вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, verbose_name='полный текст вопроса'),
        ),
    ]
