# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 08:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20160314_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_questions', to=settings.AUTH_USER_MODEL, verbose_name='список пользователей, поставивших "лайк"'),
        ),
    ]
